name: Deploy Ecom API to EKS

on:
  push:
    branches:
      - main
    paths:
      - 'ecom-api-modern/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v5
